<?php

const CLOTHES_IBLOCK_ID = 2;
const SLIDER_IBLOCK_ID = 5;
const GOAL_IBLOCK_ID = 6;
const ADVANTAGES_IBLOCK_ID = 7;

const FAQ_IBLOCK_ID = 8;
const CREDIT_SECTION_ID = 16;
const DELIVERY_SECTION_ID = 17;
const RETURN_SECTION_ID = 18;
const REVIEW_SECTION_ID = 19;

const CONTACT_IBLOCK_ID = 9;
const SHOP_SECTION_ID = 20;
const SERVICE_SECTION_ID = 21;
const OFFICE_SECTION_ID = 22;