<?php

const CLOTHES_IBLOCK_ID = 2;
const SLIDER_IBLOCK_ID = 5;
const GOAL_IBLOCK_ID = 6;
const ADVANTAGES_IBLOCK_ID = 7;

const FAQ_IBLOCK_ID = 8;

const CREDIT_SECTION_ID = 16;
const DELIVERY_SECTION_ID = 17;
const RETURN_SECTION_ID = 18;
const REVIEW_SECTION_ID = 19;